### ISSUE TITLE
vnet 开了2天又炸了

### ISSUE THREAD

**Issue by ssrpanel** [rc452860/vnet#54]
还好我做了节点离线提醒，马上就监测到了
```
[root@ONEVPS190125054659 vnet]# tail -f vnet.log 
INFO 2019-03-05 06:30:58 proxy.go[117] proxyRequest: 116.16.5.138:20866 <----5435:tcp----> log-sdk.gifshow.com:80
panic: interface conversion: interface {} is nil, not []record.ConnectionProxyRequest

goroutine 1217 [running]:
github.com/rc452860/vnet/proxy/server.(*ProxyService).proxyRequest(0xc420318700, 0x9b51e0, 0xc4202ede60, 0x9b51e0, 0xc425346a20, 0x9b51e0, 0xc425346de0, 0x9b71a0, 0xc428047480)
	/home/travis/gopath/src/github.com/rc452860/vnet/proxy/server/proxy.go:111 +0x92e
github.com/rc452860/vnet/proxy/server.(*ProxyService).route(0xc420318700)
	/home/travis/gopath/src/github.com/rc452860/vnet/proxy/server/proxy.go:87 +0x324
created by github.com/rc452860/vnet/proxy/server.(*ProxyService).TrafficMeasure
	/home/travis/gopath/src/github.com/rc452860/vnet/proxy/server/proxy.go:65 +0x65
```

**Comment by ssrpanel** [comment]
感觉是内存没有正确释放，我另一台的内存占用已经飙升至30%了

**Comment by NeedforGit** [comment]
请问怎么开机启动啊？ 我用的是debian9 设置了 rc.local, 内容是 bash /root/vnet/run.sh, 但是开机启动不了。 求助！

**Comment by rc452860** [comment]
谁写的你找谁。哈哈哈哈。我不认可这种方式。

**Comment by NeedforGit** [comment]
> 谁写的你找谁。哈哈哈哈。我不认可这种方式。

哈哈哈，我自己按照之前的ss比葫芦画瓢，瞎弄的。看来这种方式不行啊！
请问用那种方式才能开机启动呢？

**Comment by vft9nesd** [comment]
rc.local可以啊  你先看你的bash****  能运行不

**Comment by NeedforGit** [comment]
> rc.local可以啊 你先看你的bash**** 能运行不

直接bash不行，运行不了。是不是需要改什么路径之类的？请指教！

**Comment by rc452860** [comment]
你有没有bash还是个问题哦

**Comment by NeedforGit** [comment]
> 你有没有bash还是个问题哦

有，在子目录中 bash run.sh  能运行。 但是 bash /root/vnet/run.sh  这样运行不了

**Comment by rc452860** [comment]
那就是他脚本写的有问题

**Comment by NeedforGit** [comment]
> rc.local可以啊 你先看你的bash**** 能运行不

bash的不行，期待你的 supervisor
